"""empty message

Revision ID: 3227e9472cfd
Revises: 4a0537491ef4
Create Date: 2023-01-29 15:23:34.267462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3227e9472cfd'
down_revision = '4a0537491ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mug_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.drop_constraint('cart_mugs_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mugs', ['mug_id'], ['id'])
        batch_op.drop_column('mugs_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mugs_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_mugs_id_fkey', 'mugs', ['mugs_id'], ['id'])
        batch_op.drop_column('quantity')
        batch_op.drop_column('mug_id')

    # ### end Alembic commands ###
